import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { useEffect, useRef } from 'react';
import Link from 'next/link';

// MUI Icons
import MenuIcon from '@mui/icons-material/Menu';
import CloseIcon from '@mui/icons-material/Close';

// Components Import
import Header from '../components/Header';
import CompanyLogos from '../components/CompanyLogos';
import OurPrograms from '../components/OurPrograms';
import ChooseUs from '../components/ChooseUs';
import Pricing from '../components/Pricing';
import Calculator from '../components/Calculator';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';

export default function Home() {

  return (
    <div className={[styles.container, styles.container].join("")}>
      <Head>
        <title>Blazefit - Be Fit, Be You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} id="main">
        <Navbar />
        <Header />
        <CompanyLogos />
        <OurPrograms />
        <ChooseUs />
        <Pricing />
        <Calculator />
      </main>
      <Footer />

    </div>
  )
}